

hello-world:
    path:     /helloworld
    defaults:
        _controller: OCPlatformBundle:Advert:index

bye-world:
   path:      /byeworld
   defaults:
       _controller: OCPlatformBundle:Advert:byeWorld
